# Generated by Django 2.1.4 on 2018-12-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert_brand', models.CharField(max_length=30)),
                ('advert_model', models.CharField(max_length=30)),
                ('advert_category', models.CharField(max_length=30)),
                ('advert_price', models.IntegerField()),
                ('advert_owner', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'advert',
            },
        ),
    ]
